# Generated by Django 6.0.7 on 2026-09-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desciption',
            new_name='description',
        ),
    ]
